### ISSUE TITLE
CF bug report by ImDerpyMelon

### ISSUE THREAD

**Issue by gbl** [ModProg/BlockMeter#14]
about everything rendering in white - I had a similar problem in my Grid mod. Some other mods - the ones I know about are Fabritone and VoxelMap when rendering waypoints in Beacons-only-mode, do a `RenderHelper.enableLighting()` which they don't revert. Calling `RenderHelper.disableLighting()` before rendering fixed the problem for me.

**Comment by ModProg** [comment]
Thanks for the tip
