### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by TiboOpGithub** [ModProg/BlockMeter#25]
Hi!
I used this mod for a while and it worked (and was very helpful) but since a saturday in january it stopped working. I don't know exactly why. Maybe incompatible with a mod or something else? I hope you can help me
Mods:
![image](https://user-images.githubusercontent.com/95926002/153665054-91f409a7-7145-4501-bccb-f561184297cd.png)
Video:
https://youtu.be/otoA_Bubr2I

**Comment by ModProg** [comment]
Difficult to say. Did you add any new mods around that time? 

And could you maybe share the logs if anything shows up in there during this happening.


I'll try to make a 1.17 build of the current state so you can test if that fixes it.

**Comment by TiboOpGithub** [comment]
[latest.log](https://github.com/ModProg/BlockMeter/files/8053409/latest.log)

**Comment by ModProg** [comment]
> [latest.log](https://github.com/ModProg/BlockMeter/files/8053409/latest.log)

I didn't find anything if you could try it in a fresh minecraft instance without over mods that would be great, I'll try to reproduce it when I find time, but the amount of mods makes that hard to test quickly.

**Comment by TiboOpGithub** [comment]
Magic is real! Suddenly it works again, no idea why but fine. Thanks for the help and the amazing mod :)
