### ISSUE TITLE
Clarification on ModUpdater support

### ISSUE THREAD

**Issue by jn64** [ModProg/BlockMeter#29]
Is it still supported? Should it be removed?

ModUpdater was [last updated 2 years ago for 1.16](https://www.curseforge.com/minecraft/mc-mods/modupdater/files/all).

This mod [checks a file for updates](https://github.com/ModProg/BlockMeter/blame/c369371561d40449db986700233c28229430a8a4/src/main/resources/fabric.mod.json#L15) that [is also 2 years old](https://github.com/gbl/ModVersionInfo/blob/master/BlockMeter.json).

The reason I bring it up is because it still prints this warning in current versions of Minecraft + BlockMeter which may be confusing to users:

```
[22:58:05] [main/WARN]: Warnings were found!
 - Mod 'Block Meter' (blockmeter) 1.6 recommends version 1.1.7 or later of modupdater, which is missing!
	 - You should install version 1.1.7 or later of modupdater for the optimal experience.
```

The CurseForge and Modrinth pages for this mod also mentions ModUpdater.

**Comment by ModProg** [comment]
Good catch, I'll investigate this, https://github.com/ReviversMC/modget-minecraft might be an alternative.

**Comment by ModProg** [comment]
I removed all references to modupdater
