### ISSUE TITLE
[Suggestion]with freecam from tweakeroo

### ISSUE THREAD

**Issue by 100210110** [ModProg/BlockMeter#41]
Hope to be compatible with 'freecam from tweakeroo'.
Use this mod after opening the free camera, select the box or the box in front of the body, the relative experience is not very good in some inconvenient machines, so you can hope to be compatible with the out-of-body function, choose the box that the camera looks at when the soul is out of the body.
soul out of the body(灵魂出窍) ==> Free camera(自由摄像机)
Hope the translation is accurate，thanks

**Comment by ModProg** [comment]
This is something I wanted to have my self at some point already, I think it should be possible, but I might need to rework how the input works.

I'm not sure how the tweakeroo free cam works, and how to detect that it is active and what block it is looking at. Currently busy with university, but I hope to get to working on BlockMeter again in a few weeks.

**Comment by ModProg** [comment]
https://github.com/ModProg/BlockMeter/releases/tag/v1.11.0
