### ISSUE TITLE
(1.10.2) Crash on 1.20.1

### ISSUE THREAD

**Issue by syntacticsplenda** [ModProg/BlockMeter#45]
Relevant log - https://hst.sh/dugowinoro.yaml

Downgrading to 1.10.1 fixed the issue. Probably a conflict with another mod I have installed, but I didn't do any testing.

**Comment by syntacticsplenda** [comment]
Perhaps this isn't a bug and 1.10.2 simply isn't compatible with 1.20.1? It would make sense if the underlying mapping changed.

In that case, this release was incorrectly labeled on Modrinth as being compatible with 1.20-1.20.2.

**Comment by ModProg** [comment]
it's the latter, fixed it now
