### ISSUE TITLE
Black screen when using

### ISSUE THREAD

**Issue by Stephendo0318** [ModProg/BlockMeter#49]
Every time i press the keybind and then press right mouse button on a block it gives me a black screen until i press the keybind again.
My minimap is still being displayed over the black grayish screen though.

**Comment by Stephendo0318** [comment]
Nevermind i found out the problem was my shader.  >_>

**Comment by ModProg** [comment]
Yeah, shaders are always an issue with rendering custom shapes. Most shaders should work though in my experience.
