### ISSUE TITLE
Blockmeter runs on 1.20.4, but crashes under unknown condition.

### ISSUE THREAD

**Issue by kmirai88** [ModProg/BlockMeter#50]
Minecraft version: 1.20.4
Blockmeter version: 1.11.0 (1.20.2 Fabric) 
I was running Blockmeter on the latest 1.20 version (1.20.4). The mod does load fine and had no issues with it at first. I had two different colour measurements going at the same time, when my game suddenly crashes. I have included the game log when it happened.

Crash Log:
[crash-2024-01-03_20.07.34-client.txt](https://github.com/ModProg/BlockMeter/files/13894099/crash-2024-01-03_20.07.34-client.txt)

**Comment by ModProg** [comment]
fixed in version https://github.com/ModProg/BlockMeter/releases/tag/v1.12.0
