### ISSUE TITLE
[Suggestion] Block Meter Item

### ISSUE THREAD

**Issue by JasdanVM** [ModProg/BlockMeter#51]
Could you add an Overlay Item that can be crafted?
I think this would make for a better collaborative experience on servers, increases immersion, and would free up a keybind.

**Comment by ModProg** [comment]
This is meant as a client side mod, the server component is only there to allow syncing the local boxes.

I think the feature you're proposing would be a separate mod. If anyone is interested in developing one, feel free to reuse code from this repo.
