### ISSUE TITLE
1.20.6?

### ISSUE THREAD

**Issue by LordEnder-Kitty** [ModProg/BlockMeter#54]
As a modder i know that rendering is annoying, but is there any plan for 1.20.6 support? this mod is extremely useful for me and i would at least like to know if it's planned or if not, when it will next update.

**Comment by ModProg** [comment]
Def planned, currently not playing a lot so the update slipped my radar.

**Comment by ModProg** [comment]
https://modrinth.com/mod/blockmeter/version/1.13.0 Usually it's not too bad to do for Blockmeter
