### ISSUE TITLE
[1.20.6] Game crashes on startup

### ISSUE THREAD

**Issue by DlljsCodes** [ModProg/BlockMeter#55]
Game crashes on startup on 1.20.6 with [mod version 1.12.0](https://github.com/ModProg/BlockMeter/releases/tag/v1.13.0).

Is the jar file labelled correctly?

Crash log: [crash-2024-06-12_18.36.53-client.txt](https://github.com/user-attachments/files/15808864/crash-2024-06-12_18.36.53-client.txt)

**Comment by ModProg** [comment]
Oh, seems like I messed up the upgrade, I'll have a look into it

**Comment by ModProg** [comment]
The new release I cut a few hours ago should work.
