### ISSUE TITLE
Shaders causes labelboxes to be black

### ISSUE THREAD

**Issue by horseloyal** [ModProg/BlockMeter#57]
Without shaders:
![image](https://github.com/ModProg/BlockMeter/assets/171438743/669bd279-46e8-4e0e-9597-f71248557e21)

With shaders:
![image](https://github.com/ModProg/BlockMeter/assets/171438743/1300e956-87d0-4406-b3cb-49c8452ac533)

I'm using Iris 1.7, Sodium 0.5.8, & Complementary Unbound r5.0.1

**Comment by horseloyal** [comment]
Also while I'm here; reminder that 1.21 was released on the 13th (one day after you released the 1.20.6 update)

**Comment by ModProg** [comment]
Yeah, I'm looking into 1.21, but there seem to be some rendering issues even without shaders :D.

Shaders are always a bit interesting for things like this, but maybe my fixes for 1.21 will fix it for this shader as well.

**Comment by horseloyal** [comment]
> Yeah, I'm looking into 1.21, but there seem to be some rendering issues even without shaders :D.
> 
> Shaders are always a bit interesting for things like this, but maybe my fixes for 1.21 will fix it for this shader as well.

Good luck, this mod is a god send

**Comment by ModProg** [comment]
Fixed in #58
